<a href="https://colab.research.google.com/github/nephelim74/machinelearn/blob/main/IM_dz1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

actual_values = np.array([100, 150, 200, 250])  # Фактические значения
predicted_values = np.array([90, 140, 180, 270])  # Предсказанные значения

1. Среднеквадратичная ошибка (MSE)

In [2]:
# Вычисление квадратов разниц
squared_errors = (actual_values - predicted_values) ** 2

# Вычисление MSE
mse = np.mean(squared_errors)

print("Квадраты разниц:", squared_errors)
print("Среднеквадратичная ошибка (MSE):", mse)

Квадраты разниц: [100 100 400 400]
Среднеквадратичная ошибка (MSE): 250.0


2. Средняя абсолютная ошибка (MAE)

In [3]:
# Вычисление абсолютных разниц
absolute_errors = np.abs(actual_values - predicted_values)

# Вычисление MAE
mae = np.mean(absolute_errors)

print("Абсолютные разницы:", absolute_errors)
print("Средняя абсолютная ошибка (MAE):", mae)

Абсолютные разницы: [10 10 20 20]
Средняя абсолютная ошибка (MAE): 15.0


Анализ результатов:
MSE (250.0):

MSE сильнее штрафует за большие ошибки, так как использует квадраты разниц.

В данном случае ошибки (10, 10, 20, 20) были возведены в квадрат, что привело к увеличению вклада больших ошибок (20 → 400).

MAE (15.0):

MAE менее чувствительна к выбросам, так как использует абсолютные значения разниц.

В данном случае ошибки (10, 10, 20, 20) были усреднены без возведения в квадрат.

Интерпретация:

Чем меньше значение MSE или MAE, тем лучше точность модели.

В данном случае:

MSE = 250.0 указывает на то, что модель допускает значительные ошибки, особенно в случаях, где разница между фактическими и предсказанными значениями велика.

MAE = 15.0 показывает, что в среднем модель ошибается на 15 единиц.

Сравнение MSE и MAE:
MSE:

Подходит для случаев, когда большие ошибки критичны и должны быть минимизированы.

Чувствительна к выбросам.

MAE:

Подходит для случаев, когда все ошибки имеют одинаковый вес.

Менее чувствительна к выбросам.

Итог:
MSE = 250.0

MAE = 15.0

Лучшая точность предсказания достигается при меньших значениях MSE и MAE. В данном случае модель имеет среднюю точность, но есть возможность улучшить её, уменьшив ошибки, особенно в случаях с большими отклонениями (например, для последнего значения, где ошибка составила 20 единиц).

